### ISSUE TITLE
Suggestion for the problem window

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#35]
Maybe in the problem window.
All the line can be write in red at the beginiing when this one are no check by the user, and the user can change the color manually in green, orange.
The next time we look this window we can see immediatly the new problems, the problem we think are ok, the problem must be resolve, etc.

**Comment by Manindra29** [comment]
These errors are mostly syntax or compiler errors and are meant to be resolved pretty quickly. What you're suggesting seems more like a todo app feature. Designing that would be a bit excess don't you think? :)

Right now, the development focus is more on fixing the last remaining bugs and making PDE X stable, rather than adding complex features.

**Comment by knupel** [comment]
it's just an ergonomic and graphical suggestion, the color to read is good and easyer. But I understand your goal to focus on the main.
