### ISSUE TITLE
Bad files saved when modifying sketches

### ISSUE THREAD

**Issue by ale2x72** [processing/processing-experimental#49]
This started to occur to me a few days ago. After making a few tweaks to an existing sketch and saving it, this was what I got:
![processing_ugh](https://f.cloud.github.com/assets/6969618/2432297/7e905028-ad5e-11e3-995e-839648b662a2.png)

It also gave me the "No such file or directory" error when saving manually (I don't know if autosave was active or not, after installing PDE X i didn't make any preference changes).
I don't know if this could be due to PDE X, but after several attempts (such as revert to a previous Processing version), switching back to Java eliminated the problem. So PDE X seems to be the cause. 

I hope this bug (if actually due to PDE X) will be corrected in the future, as I loved using PDE X and wish to be able to use it again very soon!

**Comment by Manindra29** [comment]
Yes, a critical bug was found in the autosave feature and is causing things to break with the latest version of PDE X. Work has begun on the next release and an update can be expected in the next few weeks. In the meantime, please consider rolling back to the previous PDE X release - https://github.com/processing/processing-experimental/releases/tag/1.0.2b

**Comment by Manindra29** [comment]
Now fixed in version [1.0.4b](https://github.com/processing/processing-experimental/releases/tag/1.0.4b). My sincere apologies for your data loss. It was wrong of me to release an untested feature without adding an option to enable/disable it. I've learnt a lesson and I shall ensure this sort of thing doesn't happen again in the future.

Note that PDE X 1.0.4b requires Processing 2.1.2 or above
