### ISSUE TITLE
boolean problem

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#73]
When you write a boolean var at the top, PDE indicate an error "Syntax error on "boolean", new expected", but not with a int var or when the void setup() is a the top, like this
![capture decran 2014-06-25 a 15 26 47](https://cloud.githubusercontent.com/assets/3332269/3385660/a7240e78-fc6c-11e3-9be4-f8a91c04145c.png)
![capture decran 2014-06-25 a 15 27 06](https://cloud.githubusercontent.com/assets/3332269/3385661/a72636bc-fc6c-11e3-89c7-50abea1377d8.png)
![capture decran 2014-06-25 a 15 26 25](https://cloud.githubusercontent.com/assets/3332269/3385662/a728f474-fc6c-11e3-81cc-139b3648ad82.png)

**Comment by Manindra29** [comment]
Fixed with https://github.com/processing/processing/commit/fdf2e3203bd6c33cdf97675209aa2985d39776c3

It's expected that the user begins his sketch with void setup() before adding other methods. Internally code preprocessing is performed based on the presence/absence of setup() method, hence the minor bug.
